[tool.poetry]
name = "neovim-python3"
version = "0.1.0"
description = ""
authors = ["kefi550"]

[tool.poetry.dependencies]
python = "^3.8"
pynvim = "^0.4.1"
neovim = "^0.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

