let g:config_dir = expand('~/.config/vim')
let &runtimepath=&runtimepath . ',' . g:config_dir
let &runtimepath=&runtimepath . ',' . g:config_dir . '/ovim'
let &runtimepath=&runtimepath . ',' . g:config_dir . '/dein'
let &runtimepath=&runtimepath . ',' . g:config_dir . '/color'

" キーマッピング
runtime! mapping.rc.vim

" オプション
runtime! options.rc.vim

" dein
runtime! dein/dein.rc.vim
