[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
#hook_post_update = '''
#  if dein#util#_is_windows()
#    let cmd = 'tools\\update-dll-mingw'
#  elseif dein#util#_is_cygwin()
#    let cmd = 'make -f make_cygwin.mak'
#  elseif executable('gmake')
#    let cmd = 'gmake'
#  else
#    let cmd = 'make'
#  endif
#  let g:dein#plugin.build = cmd
#'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_completion_start_length = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'     

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/unite.vim'

#ディレクトリ表示
[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = '''
  " Use vimfiler instead of default filer.
  let g:vimfiler_as_default_explorer = 1
  " Open filer
  noremap <silent> :tree :VimFiler -split -simple -winwidth=30 -no-quit
  nnoremap <silent> <Leader>fi :<C-u>VimFilerBufferDir -split -simple -winwidth=24 -no-quit<ENTER>
  nnoremap <silent> <Leader>fi :<C-u>VimFiler -split -simple -winwidth=24 -no-quit<ENTER>
  " noremap <C-X><C-T> :VimFiler -split -simple -winwidth=30 -no-quit<ENTER>
  " Don't let <CR> enter the directory but let it open the directory
  autocmd FileType vimfiler nmap <buffer> <CR> <Plug>(vimfiler_expand_or_edit)
  " Automatically open vimfiler on start
  " autocmd VimEnter * VimFiler -split -simple -winwidth=29 -no-quit
'''

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'kana/vim-operator-user'

##ディレクトリ表示
#[[plugins]]
#repo = 'scrooloose/nerdtree'

# カッコ補完
[[plugins]]
repo = 'Townk/vim-autoclose'

# yamlインデント
[[plugins]]
repo = 'chase/vim-ansible-yaml'

# syntax check
[[plugins]]
repo =  'scrooloose/syntastic'


# ヤンクしたとこが一瞬ハイライト
[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
hook_source = '''
  map y <Plug>(operator-flashy)
  nmap Y <Plug>(operator-flashy)$
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_post_update = '''
  source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

##############################################
# コード補完
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = ['python']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {
        \ 'python': ['pyls'],
  \ }
'''
##############################################
