## LSP
# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# hook_add = '''
# lua << EOF
#   local opts = {noremap=true, silent=true}
#   vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
#   vim.keymap.set('n', '<space>h', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
# EOF
# '''
