[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
#hook_post_update = '''
#  if dein#util#_is_windows()
#    let cmd = 'tools\\update-dll-mingw'
#  elseif dein#util#_is_cygwin()
#    let cmd = 'make -f make_cygwin.mak'
#  elseif executable('gmake')
#    let cmd = 'gmake'
#  else
#    let cmd = 'make'
#  endif
#  let g:dein#plugin.build = cmd
#'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'junegunn/vim-emoji'
hook_post_source = '''
  set completefunc=emoji#complete
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/.config/vim/ovim/cheetsheet.md'
'''


[[plugins]]
repo = 'tpope/vim-surround'

#ディレクトリ表示
#[[plugins]]
#repo = 'Shougo/vimfiler'
#hook_add = '''
#  " Use vimfiler instead of default filer.
#  let g:vimfiler_as_default_explorer = 1
#  " Open filer
#  noremap <silent> :tree :VimFiler -split -simple -winwidth=30 -no-quit
#  nnoremap <silent> <Leader>fi :<C-u>VimFilerBufferDir -split -simple -winwidth=24 -no-quit<ENTER>
#  nnoremap <silent> <Leader>fi :<C-u>VimFiler -split -simple -winwidth=24 -no-quit<ENTER>
#  " noremap <C-X><C-T> :VimFiler -split -simple -winwidth=30 -no-quit<ENTER>
#  " Don't let <CR> enter the directory but let it open the directory
#  autocmd FileType vimfiler nmap <buffer> <CR> <Plug>(vimfiler_expand_or_edit)
#  " Automatically open vimfiler on start
#  " autocmd VimEnter * VimFiler -split -simple -winwidth=29 -no-quit
#'''

# ディレクトリ表示
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'kana/vim-operator-user'

# カッコ補完
[[plugins]]
repo = 'Townk/vim-autoclose'

# yamlインデント
[[plugins]]
repo = 'chase/vim-ansible-yaml'
hook_add='''
  let g:ansible_options = {'ignore_blank_lines': 0}
'''

# syntax check
[[plugins]]
repo =  'scrooloose/syntastic'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

## go
#[[plugins]]
#repo = 'fatih/vim-go'
#hook_add='''
#  let g:go_term_enabled = 1
#  let g:go_term_mode = "split"
#  let g:go_highlight_types = 1
#  let g:go_highlight_fields = 1
#  let g:go_highlight_functions = 1
#  let g:go_highlight_function_calls = 1
#  let g:go_highlight_operators = 1
#  let g:go_highlight_extra_types = 1
#  let g:go_highlight_build_constraints = 1
#  let g:go_highlight_generate_tags = 1
#
#  let g:go_auto_type_info = 1
#  " let g:go_auto_sameids = 1
#'''

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'mattn/vim-gorun'

[[plugins]]
repo = 'mattn/vim-goimpl'

# ヤンクしたとこが一瞬ハイライト
[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
hook_source = '''
  map y <Plug>(operator-flashy)
  nmap Y <Plug>(operator-flashy)$
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
[[plugins]]
repo = 'junegunn/fzf.vim'

#[[plugins]]
#repo = 'w0rp/ale'
#hook_add='''
#let g:ale_linters = {
#\  'markdown': ['textlint'],
#\ }
#" let g:ale_completion_enabled = 1
#let g:ale_enabled = 1
#'''

##############################################

## 色
#[[plugins]]
#repo = 'itchyny/lightline.vim'
#hook_post_update = '''
#  source ~/.config/vim/nvim/plugins/lightline.vim
#'''

#[[plugins]]
#repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'default'
  let g:airline_theme='molokai'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'fatih/molokai'
#############################################
