[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {
  \     '*': {'hook/time/enable': '1'},
  \    'json': {
  \        'outputter/buffer/filetype': 'json',
  \        'command': 'jq',
  \        'cmdopt': '.',
  \        'exec': 'cat %s | sed -z "s/\n//g" | %c %o',
  \    }
  \}
'''

# airline
######################################################################
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'default'
  let g:airline_theme='molokai'
'''
######################################################################

### LSP


