## LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  " let g:lsp_diagnostics_signs_warning = {'text': '💩'}
  " let g:lsp_diagnostics_signs_error = {'text': '💩'}
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['python', 'go', 'sh', 'html', 'terraform', 'tf']
depends = ['asyncomplete.vim', 'vim-lsp']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
